//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bishop.
        /// </summary>
        internal static string Bishop {
            get {
                return ResourceManager.GetString("Bishop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string Chess {
            get {
                return ResourceManager.GetString("Chess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Game.
        /// </summary>
        internal static string ContinueGame {
            get {
                return ResourceManager.GetString("ContinueGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game data found.
        /// </summary>
        internal static string EmptyGameDataMessage {
            get {
                return ResourceManager.GetString("EmptyGameDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Game Data.
        /// </summary>
        internal static string EraseData {
            get {
                return ResourceManager.GetString("EraseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedGame.json.
        /// </summary>
        internal static string FileContainingGameData {
            get {
                return ResourceManager.GetString("FileContainingGameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChessBoardState.json.
        /// </summary>
        internal static string FileContainingNewGameData {
            get {
                return ResourceManager.GetString("FileContainingNewGameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string ImageFolder {
            get {
                return ResourceManager.GetString("ImageFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        internal static string Knight {
            get {
                return ResourceManager.GetString("Knight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pawn.
        /// </summary>
        internal static string Pawn {
            get {
                return ResourceManager.GetString("Pawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rook.
        /// </summary>
        internal static string Rook {
            get {
                return ResourceManager.GetString("Rook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveGame {
            get {
                return ResourceManager.GetString("SaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Piece.
        /// </summary>
        internal static string SelectPiece {
            get {
                return ResourceManager.GetString("SelectPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!! {0} Wins !!!.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
    }
}
